# 欢迎使用 TRSS Yunzai Plugin ! 作者：时雨🌌星空
# 按 Ctrl+Q Y 保存退出
# 参考：https://gitee.com/TimeRainStarSky/TRSS-Plugin

GenshinVoice:
  api: "" # API 地址

RealESRGAN:
  api: "" # API 地址

ChatGPT:
  api: "" # API 地址
  tokenapi: "" # Token API 地址
  username: "" # OpenAI 账号
  password: "" # OpenAI 密码
  sessionToken: ""